services:
  nats-server:
    image: nats:latest
    ports:
      - 8222:8222

  client-gateway:
    build: ./client-gateway
    ports:
      - "3000:3000"
    environment:
      - PORT=3000
      - NATS_SERVERS=nats://nats-server:4222
    volumes:
      - ./client-gateway/src:/usr/src/app/src
    command: npm run start:dev --watch

  auth-ms:
    depends_on:
      - auth-db
    build: ./auth-ms
    ports:
      - "3004:3004"
    environment:
      - PORT=3004
      - NATS_SERVERS=nats://nats-server:4222
      - AUTH_DATABASE_URL=${AUTH_DATABASE_URL}
      - JWT_SECRET=${JWT_SECRET}
    volumes:
      - ./auth-ms/src:/usr/src/app/src
    command: npm run start:dev --watch

  products-ms:
    build: ./products-ms
    ports:
      - "3001:3001"
    environment:
      - PORT="3001"
      - DATABASE_URL=file:./dev.db
      - NATS_SERVERS=nats://nats-server:4222
    volumes:
      - ./products-ms/src:/usr/src/app/src
    command: npm run start:dev --watch
  
  orders-ms:
    depends_on:
      - orders-db
    build: ./orders-ms
    ports:
      - "3002:3002"
    environment:
      - PORT="3002"
      - DATABASE_URL=postgresql://postgres:1234@orders-db:5432/orderdb?schema=public
      - NATS_SERVERS=nats://nats-server:4222
    volumes:
      - ./orders-ms/src:/usr/src/app/src
    command: npm run start:dev --watch

  payments-ms:
    build: ./payments-ms
    ports:
      - "${PAYMENT_MS_PORT}:${PAYMENT_MS_PORT}"
    environment:
      - PORT=${PAYMENT_MS_PORT}
      - NATS_SERVERS=nats://nats-server:4222
      - STRIPE_SECRET=${STRIPE_SECRET}
      - STRIPE_ENDPOINT_SECRET=${STRIPE_ENDPOINT_SECRET}
      - STRIPE_SUCCESS_URL=${STRIPE_SUCCESS_URL}
      - STRIPE_CANCEL_URL=${STRIPE_CANCEL_URL}
    volumes:
      - ./payments-ms/src:/usr/src/app/src
    command: npm run start:dev --watch

  orders-db:
    container_name: order_database
    image: postgres:16.2
    restart: always
    volumes:
      - ./orders-ms/postgres:/var/lib/postgresql/data
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=1234
      - POSTGRES_DB=orderdb

  auth-db:
    container_name: auth_database
    image: mongo
    restart: always
    command: ["mongod", "--replSet", "rs0", "--bind_ip_all"]
    volumes: 
      - mongodb_data:/data/db
    ports:
      - 27017:27017
volumes:
  mongodb_data:
